# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2019-01-17 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='md5',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
    ]
